INSERT INTO roles (role_name) VALUES ('ROLE_USER');
INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (role_name) VALUES ('ROLE_MODERATOR');

INSERT INTO countries (country_name) VALUES ('USA');
INSERT INTO countries (country_name) VALUES ('Canada');
INSERT INTO countries (country_name) VALUES ('Mexico');
INSERT INTO countries (country_name) VALUES ('Great Britain');
INSERT INTO countries (country_name) VALUES ('Germany');
INSERT INTO countries (country_name) VALUES ('France');
INSERT INTO countries (country_name) VALUES ('Italy');
INSERT INTO countries (country_name) VALUES ('Spain');
INSERT INTO countries (country_name) VALUES ('Japan');
INSERT INTO countries (country_name) VALUES ('China');
INSERT INTO countries (country_name) VALUES ('India');
INSERT INTO countries (country_name) VALUES ('Australia');
INSERT INTO countries (country_name) VALUES ('Brazil');
INSERT INTO countries (country_name) VALUES ('Russia');
INSERT INTO countries (country_name) VALUES ('South African Republic');

INSERT INTO genres (genre_name) VALUES ('Pop');
INSERT INTO genres (genre_name) VALUES ('Rock');
INSERT INTO genres (genre_name) VALUES ('Hip-Hop');
INSERT INTO genres (genre_name) VALUES ('Jazz');
INSERT INTO genres (genre_name) VALUES ('Classical');
INSERT INTO genres (genre_name) VALUES ('Electronic');
INSERT INTO genres (genre_name) VALUES ('Reggae');
INSERT INTO genres (genre_name) VALUES ('Country');
INSERT INTO genres (genre_name) VALUES ('Metal');
INSERT INTO genres (genre_name) VALUES ('Blues');
INSERT INTO genres (genre_name) VALUES ('Folk');
INSERT INTO genres (genre_name) VALUES ('Soul');
INSERT INTO genres (genre_name) VALUES ('Alternative');
INSERT INTO genres (genre_name) VALUES ('Indie');
INSERT INTO genres (genre_name) VALUES ('K-Pop');
INSERT INTO genres (genre_name) VALUES ('Trap');
INSERT INTO genres (genre_name) VALUES ('R&B');
INSERT INTO genres (genre_name) VALUES ('Dancehall');
INSERT INTO genres (genre_name) VALUES ('Lo-fi');
INSERT INTO genres (genre_name) VALUES ('Dubstep');
INSERT INTO genres (genre_name) VALUES ('Synthwave');
INSERT INTO genres (genre_name) VALUES ('Tropical House');