INSERT INTO roles (roleName) VALUES ('ROLE_USER');
INSERT INTO roles (roleName) VALUES ('ROLE_ADMIN');
INSERT INTO roles (roleName) VALUES ('ROLE_MODERATOR');

INSERT INTO countries (countryName) VALUES ('USA');
INSERT INTO countries (countryName) VALUES ('Canada');
INSERT INTO countries (countryName) VALUES ('Mexico');
INSERT INTO countries (countryName) VALUES ('Great Britain');
INSERT INTO countries (countryName) VALUES ('Germany');
INSERT INTO countries (countryName) VALUES ('France');
INSERT INTO countries (countryName) VALUES ('Italy');
INSERT INTO countries (countryName) VALUES ('Spain');
INSERT INTO countries (countryName) VALUES ('Japan');
INSERT INTO countries (countryName) VALUES ('China');
INSERT INTO countries (countryName) VALUES ('India');
INSERT INTO countries (countryName) VALUES ('Australia');
INSERT INTO countries (countryName) VALUES ('Brazil');
INSERT INTO countries (countryName) VALUES ('Russia');
INSERT INTO countries (countryName) VALUES ('South African Republic');

INSERT INTO genres (genreName) VALUES ('Pop');
INSERT INTO genres (genreName) VALUES ('Rock');
INSERT INTO genres (genreName) VALUES ('Hip-Hop');
INSERT INTO genres (genreName) VALUES ('Jazz');
INSERT INTO genres (genreName) VALUES ('Classical');
INSERT INTO genres (genreName) VALUES ('Electronic');
INSERT INTO genres (genreName) VALUES ('Reggae');
INSERT INTO genres (genreName) VALUES ('Country');
INSERT INTO genres (genreName) VALUES ('Metal');
INSERT INTO genres (genreName) VALUES ('Blues');
INSERT INTO genres (genreName) VALUES ('Folk');
INSERT INTO genres (genreName) VALUES ('Soul');
INSERT INTO genres (genreName) VALUES ('Alternative');
INSERT INTO genres (genreName) VALUES ('Indie');
INSERT INTO genres (genreName) VALUES ('K-Pop');
INSERT INTO genres (genreName) VALUES ('Trap');
INSERT INTO genres (genreName) VALUES ('R&B');
INSERT INTO genres (genreName) VALUES ('Dancehall');
INSERT INTO genres (genreName) VALUES ('Lo-fi');
INSERT INTO genres (genreName) VALUES ('Dubstep');
INSERT INTO genres (genreName) VALUES ('Synthwave');
INSERT INTO genres (genreName) VALUES ('Tropical House');